imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        logstash-debug:
            type: stream
            level: debug
            path:  "%kernel.logs_dir%/%kernel.environment%.json.log"
            formatter: monolog_logstash_formatter
        console:
            type:  console
